[package]
name = "omega-learning-tasks"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
automata = { path = "../../crates/automata" }
automata-learning = { path = "../../crates/automata-learning" }
csv = "1.3.1"
itertools = "0.13.0"
rayon = "1.10.0"
